### ISSUE TITLE
excluded is broken

### ISSUE THREAD

**Issue by incredincomp** [incredincomp/the_hunting#12]
wont exclude domains from recon stage running single domain in -d and single subdomain in -e

**Comment by 1efty** [comment]
So... 

```bash
./the_hunting.sh -d test.com -e sub.test.com
```

doesn't work properly?

**Comment by incredincomp** [comment]
Negative, I think I reversed the logic at a point and now I’m just kind
of confused. I need it to check if -e/$excluded has any values in it(array)
and then if it does, do the/some shit, otherwise echo nothing done. I broke
the variable check tho I think, then reversed the if else around. Will look
into it tonight tho

**Comment by incredincomp** [comment]
@1efty https://serverfault.com/a/477506 this is where I got the idea to try and eval an array, but the shit always returns empty for some reason right now, though I dont think it is actually empty, just keeps returning empty

**Comment by incredincomp** [comment]
know what i bet would help? feeding it subdomains with the stupid comma

**Comment by incredincomp** [comment]
from amass| - | -
-- | -- | --
-bl | Blacklist of subdomain names that will not be investigated | amass enum -bl blah.example.com -d example.com
-blf | Path to a file providing blacklisted subdomains | amass enum -blf data/blacklist.txt -d example.com


Ill just set `-blf` to excluded.txt or we can feed excluded to the script like $target is. Since just amass is info grabbing rn, I only need to worry about what it finds really.

**Comment by incredincomp** [comment]
635223eb4c50d02fdc661e2afce5ad8c553e8c39
