### ISSUE TITLE
install.sh doesn't respect command line options

### ISSUE THREAD

**Issue by 1efty** [incredincomp/the_hunting#20]
Seems that from a fresh droplet, `install.sh` doesn't respect any flags and ultimately failing to install any dependencies. 

The `logo` issue is probably because it's defined in `the_hunting.sh` and doesn't necessarily source it from that script at any point. 

```bash
root@ubuntu-s-1vcpu-1gb-fra1-01:~/the_hunting# ./install.sh -p
./install.sh: line 4: logo: command not found
Usage: ./install.sh -[i]
Options:
  -i	-	install everything
  -u	-	update everything
  -p	-	install pre_reqs
  -t	-	install tools
  -w	-	update wordlists
  -a	-	update all tools
  -l	-	less LICENSE

root@ubuntu-s-1vcpu-1gb-fra1-01:~/the_hunting# ./install.sh -l
./install.sh: line 4: logo: command not found
Usage: ./install.sh -[i]
Options:
  -i	-	install everything
  -u	-	update everything
  -p	-	install pre_reqs
  -t	-	install tools
  -w	-	update wordlists
  -a	-	update all tools
  -l	-	less LICENSE

root@ubuntu-s-1vcpu-1gb-fra1-01:~/the_hunting# ./install.sh -i
./install.sh: line 4: logo: command not found
Usage: ./install.sh -[i]
Options:
  -i	-	install everything
  -u	-	update everything
  -p	-	install pre_reqs
  -t	-	install tools
  -w	-	update wordlists
  -a	-	update all tools
  -l	-	less LICENSE
```

**Comment by 1efty** [comment]
I've got a parse args function in one of my repositories that could potentially help all arg parsing.

https://github.com/1efty/fedora-workstation-setup/blob/8f3ff0a37cce0072c38a298fc4d8a3c3ed74f1c8/scripts/lib.sh#L135

**Comment by incredincomp** [comment]
totally havent even ran it once, so you beat me there lmao. Ill look into fixing it cause yeah, if you dont want to use axiom this would be pretty helpful, though I think it is missing a tool or two now.. maybe not tho really ill have to look. Thanks for letting me know!

**Comment by incredincomp** [comment]
great argparse you beast. im using this everywhere now, thanks XoXo
