### ISSUE TITLE
change $target before setting directory names

### ISSUE THREAD

**Issue by incredincomp** [incredincomp/the_hunting#31]
I want to delete the dot in .com and replace with - or something when setting the working directory.. I hate periods in my directory names. probably copy $target into a new variable, then sed or something and get the . out and replace with - and then save that as a new variable called something like $target_directory and use that for inside of targets/

**Comment by 1efty** [comment]
@incredincomp does it cause any issues?

**Comment by incredincomp** [comment]
8cffbe2db0aa37771e15827fe5ea47f5b9affd89
