### ISSUE TITLE
Implement tmux

### ISSUE THREAD

**Issue by incredincomp** [incredincomp/the_hunting#45]
Scans and recon can take a long time, free us from this terminal jail.

**Comment by incredincomp** [comment]
Needed `libevent-dev ncurses-dev bison pkg-config`

**Comment by incredincomp** [comment]
Build
` ` `bash
tar -zxf tmux-*.tar.gz
cd tmux-*/
./configure
make && sudo make install 
```

**Comment by incredincomp** [comment]
https://github.com/tmux/tmux/wiki/Advanced-Use#scripting-tmux

**Comment by incredincomp** [comment]
looking into this tonight now that scans are somewhat automated doing the whole `&&` hack. hate leaving my session and terminal open all the time

**Comment by incredincomp** [comment]
with this implemented, I am going to move project to v0.4.0

**Comment by incredincomp** [comment]
`dnf install tmux` #50 @1efty

**Comment by 1efty** [comment]
Already done
