### ISSUE TITLE
--file is not passing varible to subdomain option

### ISSUE THREAD

**Issue by incredincomp** [incredincomp/the_hunting#59]
cant figure out whats going on, might need a new droplet. will try again tomorrow

**Comment by incredincomp** [comment]
@1efty not sure what happened... I split recon and scan and got recon out of main and now scan stopped getting the variable from parse args... :'(

**Comment by 1efty** [comment]
See https://github.com/incredincomp/the_hunting/blob/d0e3ed1689175a4a4569da9aff2acc39d9bfc5a7/the_hunting.sh#L612

Remove quotes around `$@`. It's essentially passing everything as `$1`. Does that help?

**Comment by incredincomp** [comment]
NO SHIT HUH. Fucking shellcheck lol

**Comment by 1efty** [comment]
Same with https://github.com/incredincomp/the_hunting/blob/d0e3ed1689175a4a4569da9aff2acc39d9bfc5a7/the_hunting.sh#L629

**Comment by incredincomp** [comment]
I am actually surprised that autoclosed this... git is weird
